### ISSUE TITLE
May be enable it for PowerShell? 

### ISSUE THREAD

**Issue by waldo1001** [NAVDEMO/RenumberNavObjectIds#1]
Renumber-NAVApplicationObject -Path x -FromObject 86400 -ToObject 86404
:-)

**Comment by freddydk** [comment]
Done.

import-module "RenumberObjectIds.dll"
$RenumberList = @{}
0..49 | % { $RenumberList += @{ (52000+$_) = (80000+$_) } }
Renumber-NavObjectIds -SourceFolder "c:\DEMO\BingMaps\sources" `
                      -DestinationFolder "c:\DEMO\BingMaps\newsources" `
                      -RenumberList $RenumberList `
                      -Verbose
